version: 0.2
env:
  variables:
    REPOSITORY_URI: "428075270827.dkr.ecr.us-east-1.amazonaws.com/shopify"

phases:
  pre_build:
    commands:
      - apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update
      - apt-get install -y trivy
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 428075270827.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - trivy image $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - aws ecs update-service --cluster shopify --service shopify-app --force-new-deployment
