# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bb8d2ae7d578acfc4edc57e327eb689"
name = "barcode-scanner"
handle = "barcode-scanner-9"
application_url = "https://shipping-respond-atlantic-biodiversity.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "barcode-laitkor.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shipping-respond-atlantic-biodiversity.trycloudflare.com/auth/callback",
  "https://shipping-respond-atlantic-biodiversity.trycloudflare.com/auth/shopify/callback",
  "https://shipping-respond-atlantic-biodiversity.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
